version: "3"

services:
  web:

    image: lamarcke/game-node-web:latest

    environment:
      NODE_ENV: production
      NEXT_PUBLIC_DOMAIN_SERVER: ${NEXT_PUBLIC_DOMAIN_SERVER}
      NEXT_PUBLIC_DOMAIN_WEBSITE: ${NEXT_PUBLIC_DOMAIN_WEBSITE}
      NEXT_PUBLIC_SERVER_URL: ${NEXT_PUBLIC_SERVER_URL}
      NEXT_PUBLIC_SEARCH_URL: ${NEXT_PUBLIC_SEARCH_URL}
      NEXT_PUBLIC_MATOMO_URL: ${NEXT_PUBLIC_MATOMO_URL}
      NEXT_PUBLIC_MATOMO_SITE_ID: ${NEXT_PUBLIC_MATOMO_SITE_ID}

    networks:
      - game_node_app_public


networks:
  game_node_app_public:
    external: true

volumes:
  web:



