version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "3000:3000"

    volumes:
      - /app/node_modules
      - /app/.next

    environment:
      - NODE_ENV=production

    networks:
      - game_node_app


networks:
  game_node_app:
    external: true




