version: "3"

services:
  app:

    image: lamarcke/game-node-web:latest

    ports:
      - "3000:3000"

    environment:
      NODE_ENV: production
      NEXT_PUBLIC_DOMAIN_SERVER: ${NEXT_PUBLIC_DOMAIN_SERVER}
      NEXT_PUBLIC_DOMAIN_WEBSITE: ${NEXT_PUBLIC_DOMAIN_WEBSITE}
      NEXT_PUBLIC_SERVER_URL: ${NEXT_PUBLIC_SERVER_URL}
      NEXT_PUBLIC_SEARCH_URL: ${NEXT_PUBLIC_SEARCH_URL}

    networks:
      - game_node_app


networks:
  game_node_app:
    external: true

volumes:
  web:



